name: Build

on:
  workflow_dispatch:
    inputs:
      memfault_fw_type:
        description: Memfault Firmware Type
        type: string
        required: false
        default: "att-dev"
      build_all:
        description: Build for all targets
        type: boolean
        required: false
        default: false
      push_memory_badges:
        description: Whether to parse thingy91x build log and push memory badges
        type: boolean
        required: false
        default: false
  workflow_call:
    inputs:
      memfault_fw_type:
        type: string
        required: false
        default: "att-dev"
      nrfsdk_sha_update:
        type: boolean
        required: false
        default: false
      build_all:
        type: boolean
        required: false
        default: false
      push_memory_badges:
        type: boolean
        required: false
        default: false
    outputs:
      run_id:
        description: The run ID of the workflow to fetch artifacts from
        value: ${{ jobs.build.outputs.run_id }}
      version:
        description: The version of the firmware built on this run_id
        value: ${{ jobs.build.outputs.version }}
      ncsupdate_pr:
        description: Pull request id for west ncs pointer
        value: ${{ jobs.build.outputs.ncsupdate_pr }}

  pull_request:
    paths-ignore:
      - "tests/**"
      - "docs/**"
      - "scripts/**"
      - "README.md"
      - ".github/workflows/*.yml"
      - "!.github/workflows/build.yml"

jobs:
  build:
    runs-on: build_self_hosted
    container: ghcr.io/zephyrproject-rtos/ci:v0.27.4
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    outputs:
      run_id: ${{ github.run_id }}
      version: ${{ env.VERSION }}
      ncsupdate_pr: ${{ steps.pr.outputs.pull-request-number }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: asset-tracker-template

      - name: Initialize
        working-directory: asset-tracker-template
        run: |
          if [ ! -d "../.west" ]; then
            west init -l .
          else
            echo ".west folder already exists, skipping west init."
          fi
          if [ "$NRFSDK_SHA_UPDATE" = "true" ]; then
            NRFSDK_SHA=$(git ls-remote https://github.com/nrfconnect/sdk-nrf main | awk '{print $1}')
            sed -i "/revision:/s/\( *revision: *\).*/\1${NRFSDK_SHA}/" west.yml
            echo Configuring build on NCS rev ${NRFSDK_SHA}
            echo "NRFSDK_SHA=${NRFSDK_SHA}" >> $GITHUB_ENV
          fi
          west update -o=--depth=1 -n
          west blobs fetch hal_nordic

      - name: Install dependencies
        run: |
          # The Matter IDL is part of requirements-build.txt, but it's not available
          # in pypi so we need to install it from the source code
          MATTER_IDL_PATH=modules/lib/matter/scripts/py_matter_idl
          if [ -d $MATTER_IDL_PATH ]; then
            pip install -e $MATTER_IDL_PATH
          fi
          pip install -r nrf/scripts/requirements-build.txt
          rm -rf artifacts
          mkdir -p artifacts

      - name: Set MEMFAULT_FW_TYPE and MEMFAULT_FW_VERSION_PREFIX
        shell: bash
        run: |
          if [[ -z "${{ inputs.memfault_fw_type }}" ]]; then
            echo "MEMFAULT_FW_TYPE=att-dev" >> $GITHUB_ENV
          else
            echo "MEMFAULT_FW_TYPE=${{ inputs.memfault_fw_type }}" >> $GITHUB_ENV
          fi

          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            echo "MEMFAULT_FW_VERSION_PREFIX=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "MEMFAULT_FW_VERSION_PREFIX=0.0.0-dev" >> $GITHUB_ENV
          fi
