name: Build

on:
  workflow_dispatch:
    inputs:
      memfault_fw_type:
        description: Memfault Firmware Type
        type: string
        required: false
        default: "att-dev"
      build_all:
        description: Build for all targets
        type: boolean
        required: false
        default: false
      push_memory_badges:
        description: Whether to parse thingy91x build log and push memory badges
        type: boolean
        required: false
        default: false
  workflow_call:
    inputs:
      memfault_fw_type:
        type: string
        required: false
        default: "att-dev"
      nrfsdk_sha_update:
        type: boolean
        required: false
        default: false
      build_all:
        type: boolean
        required: false
        default: false
      push_memory_badges:
        type: boolean
        required: false
        default: false
    outputs:
      run_id:
        description: The run ID of the workflow to fetch artifacts from
        value: ${{ jobs.build.outputs.run_id }}
      version:
        description: The version of the firmware built on this run_id
        value: ${{ jobs.build.outputs.version }}
      ncsupdate_pr:
        description: Pull request id for west ncs pointer
        value: ${{ jobs.build.outputs.ncsupdate_pr }}

  pull_request:
    paths-ignore:
      - "tests/**"
      - "docs/**"
      - "scripts/**"
      - "README.md"
      - ".github/workflows/*.yml"
      - "!.github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ github.run_id }}
      version: ${{ env.VERSION }}
      ncsupdate_pr: ${{ steps.pr.outputs.pull-request-number }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: asset-tracker-template

      - name: Set MEMFAULT_FW_TYPE and MEMFAULT_FW_VERSION_PREFIX
        shell: bash
        run: |
          if [[ -z "${{ inputs.memfault_fw_type }}" ]]; then
            echo "MEMFAULT_FW_TYPE=att-dev" >> $GITHUB_ENV
          else
            echo "MEMFAULT_FW_TYPE=${{ inputs.memfault_fw_type }}" >> $GITHUB_ENV
          fi

          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            echo "MEMFAULT_FW_VERSION_PREFIX=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "MEMFAULT_FW_VERSION_PREFIX=0.0.0-dev" >> $GITHUB_ENV
          fi
