name: Manifest
on:
  pull_request_target:

permissions:
  contents: read

jobs:
  contribs:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: scripts/requirements-actions.txt

      - name: Install Python packages
        run: |
          cd test
          pip install -r scripts/requirements-actions.txt --require-hashes

