name: Manifest
on:
  pull_request_target:

permissions:
  contents: read

jobs:
  contribs:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write # to create/update pull request comments
    name: Manifest
    steps:
      - name: init
        run: |
          echo "Secret value: ${{ secrets.GITHUB_TOKEN }}"
        
      - name: Checkout the code
        uses: actions/checkout@v4 # v4.2.2
        with:
          path: test-action/test-action
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 3
          persist-credentials: false

      - name: Install Python packages
        run: |
          cd test-action/test-action
          pip install -r scripts/requirements-actions.txt --require-hashes
